### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by Boohooligan** [starsoccer/energysmartbridge#2]
# EnergySmartBridge 

A Home Assistant add-on designed to repurpose the controllers for the now defunct Lowes EnergySmart Water Heater WiFi Controller. It should be capable of supporting AO Smith, Whirlpool, and Kenmore water heaters with the compatible port, but not all have been tested. Since these controllers were rendered worthless when the cloud service shut down. they should be fairly inexpensive to acquire.

## How it Works

The controller posts the status of the water heater every 5-6 minutes to https://energysmartwaterheater.com/. Any queued setting changes are returned in the json response. Since the cloud service is now offline, you must redirect the DNS to Home Assistant where this add-on will accept and control the communication. This traffic is on port 443 which is not in use by Home Assistant by default.

# Setup Instructions

## Prerequisites
**EnergySmart 612026 Electric Water Heater Controller**

- eBay is likely your best source if you don't already have one.

**A 2.4Ghz WiFi Network**

- The controller is not able to use 5Ghz wifi

**Compatible Water Heater** 

- Models are listed on the device packaging though the list is not exhaustive. AO Smith, Whirlpool, and Kenmore water heaters with this cover and port underneath will likely be compatible.

![smartgrid](https://github.com/starsoccer/energysmartbridge/assets/81272440/0d2f280e-50e6-4ad7-9e3b-88a4e91bde5c)
![gridport](https://github.com/starsoccer/energysmartbridge/assets/81272440/1a6cc86a-2d35-4b9c-9b35-2aa9a2f116ec)

**Ability to Control DNS on your Network**

- This can be done with Pi-hole, pfSense, and other products. This is required because you will have to tell the controller mentioned above that the domain it is trying to contact is actually on your local network and not on the internet.

**Home Assistant**

- It is recommended you use an up to date version which as of this writing is 2024.1.5
- Port 443 MUST NOT BE IN USE on your Home Assistant

## Setting It Up

**Install a MQTT Broker on Home Assistant**

1. Install "Mosquitto broker" in the add-ons section of Home Assistant. If you are using a different MQTT Broker you will need to be able to figure how the instructions differ for your setup.

2. Configure Mosquitto broker. Leave network ports default unless you need to change them for some reason. There are a few login options. I went with a login just for the broker. The format to use in the login configuration section is as follows:

`- username: YOUR-USERNAME-HERE`
`  password: YOUR-PASSWORD-HERE`

It might not be clear but there are 2 spaces before password to line it up with username in the config.

3.  Start Mosquitto broker and set to Start on Boot and Enable Watchdog

**Install Energy Smart Bridge**

1. Go back to the add-on store > 3 dots in the top right > Repositories
2. Add this to your repository list: https://github.com/starsoccer/energysmartbridge
3. 3 Dots in the top right again > Check for Updates
4. Install Energy Smart Bridge
5. Configure Energy Smart Bridge with the these settings:
- MQTT_PORT: 1883 (change this if you set a custom port in Mosquitto broker)
- MQTT_SERVER: The IP address of Home Assistant (ex. '192.168.1.100')
- MQTT_USERNAME: This is the username you configured in Mosquitto broker
- MQTT_PASSWORD: This is the password you configured in Mosquitto broker
- MQTT_PREFIX: energysmart
- MQTT_DISCOVERY_PREFIX: homeassistant
6. Start Energy Smart Bridge, set it to Start on Boot, and Enable Watchdog

**Configure your local DNS**

You need to add to your network DNS (via Pi-hole, pfSense, or some other method) the following domains to point to your Home Assistant IP address:
- energysmartwaterheater.com
- devices.irissmarthome.com

**Connect the Water Heater Controller**

It is at this point it should be pointed out that doing this could cause damage to your water heater, void your warranty, or worse. DRAGONS AHEAD, TURN BACK NOW!

It is a good idea to cut power to your water heater before installing the controller. After you physically install it and turn power back on you should continue to follow the controller's instruction manual to connect it to your network. It defaults to an AP mode so you will connect to it with another device and tell it which network to connect to.

**That's it**

If you've done all of this correctly, the controller should begin reporting data to the Energy Smart Bridge, which in turn reports it to Mosquitto broker. Entities should be automatically created in your Home Assistant.

# Some Important Notes and Caveats

**The controller reports in about every 5-6 minutes and won't pick up mode or temperature changes until it reports in. Be patient when changing settings.**

**Remote Administration setting does not matter.** It can be on or off and should not have any effect on your ability to change the temperature or mode.

**The mode as shown in Home Assistant for the water_heater entity will likely not match what your water heater's mode actually is.** This is because the entity in Home Assistant has preset mode options and they could not be changed to match. The current mapping is "heat pump" = Efficiency and "eco" = Hybrid. For this reason, there is another sensor included that will report the mode exactly as reported by the water heater rather than the translated mode.

**To change the mode, you need to send the mode the water heater knows, not the water_heater entity.** For example, instead of sending eco you would send Hybrid. You can use the mode sensor to determine the exact modes available.

**140F is the highest the temperature can be set** The actual water heater may be capable of going higher, but the controller will not set a setting higher than 140F.

**If you are using Celsius** you're on your own. I have no idea how this will work with Celsius.

**Comment by Boohooligan** [comment]
Let me know what you think so far. I was going to create another one that's kind of like "What is this, how does it work?" kind of thing, if you think it would be good info to include. 

There are a few places online where people have tried to get this working, as I'm sure you've seen, so it would be good to be able to point them here after all this time.

**Comment by starsoccer** [comment]
Updated the readme, tweaked things a bit, let me know what you think

**Comment by Boohooligan** [comment]
Looks good, a bit more concise. The mode table at the bottom has some issues. Typos and Hybrid and eco are on the wrong sides of the table. Otherwise I think it's good to go.

**Comment by starsoccer** [comment]
Whoops good catch, is it better now?

**Comment by Boohooligan** [comment]
Perfect!

**Comment by starsoccer** [comment]
Okay great. Then with that, I appreciate all of your help along the way and for the time being I am going to close this issue too
